// <auto-generated />
using System;
using FacturationTN.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FacturationTN.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260418112050_AddUserAccountProfileFields")]
    partial class AddUserAccountProfileFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FacturationTN.Models.CategorieClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("CategoriesClient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "VIP"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "PME"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Particulier"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Export"
                        });
                });

            modelBuilder.Entity("FacturationTN.Models.CategorieProduit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("CategoriesProduit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Alimentaire"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Électronique"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Textile"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Service conseil"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "Bâtiment"
                        },
                        new
                        {
                            Id = 6,
                            Nom = "Informatique"
                        });
                });

            modelBuilder.Entity("FacturationTN.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CategorieClientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodePostal")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Fax")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FormeJuridique")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gouvernorat")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatriculeFiscale")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModePaiement")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomContact")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroRne")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PlafondCredit")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("PosteContact")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemiseParDefaut")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("SiteWeb")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone2")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeClient")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ville")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieClientId");

                    b.HasIndex("MatriculeFiscale")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("FacturationTN.Models.Facture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroFacture")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TimbreFiscal")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("NumeroFacture")
                        .IsUnique();

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("FacturationTN.Models.LigneFacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("FactureId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixUnitaireHT")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TauxTva")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FactureId");

                    b.HasIndex("ProduitId");

                    b.ToTable("LignesFacture");
                });

            modelBuilder.Entity("FacturationTN.Models.Parametres", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoContentType")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatriculeFiscale")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantTimbreFiscal")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("RaisonSociale")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Parametres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adresse = "",
                            MatriculeFiscale = "",
                            MontantTimbreFiscal = 1.000m,
                            RaisonSociale = ""
                        });
                });

            modelBuilder.Entity("FacturationTN.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategorieProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marque")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixAchatHT")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("PrixVenteHT")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("QuantiteStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RemiseMax")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SeuilAlerte")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SuiviStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TauxTva")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeProduit")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UniteMesureId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategorieProduitId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("UniteMesureId");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("FacturationTN.Models.TauxTva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Taux")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TauxTva");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = true,
                            Libelle = "Exonéré",
                            Taux = 0
                        },
                        new
                        {
                            Id = 2,
                            Actif = true,
                            Libelle = "Réduit",
                            Taux = 7
                        },
                        new
                        {
                            Id = 3,
                            Actif = true,
                            Libelle = "Intermédiaire",
                            Taux = 13
                        },
                        new
                        {
                            Id = 4,
                            Actif = true,
                            Libelle = "Normal",
                            Taux = 19
                        });
                });

            modelBuilder.Entity("FacturationTN.Models.UniteMesure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("UnitesMesure");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Pièce"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Kg"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Litre"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Mètre"
                        },
                        new
                        {
                            Id = 5,
                            Nom = "m²"
                        },
                        new
                        {
                            Id = 6,
                            Nom = "Heure"
                        },
                        new
                        {
                            Id = 7,
                            Nom = "Jour"
                        },
                        new
                        {
                            Id = 8,
                            Nom = "Forfait"
                        });
                });

            modelBuilder.Entity("FacturationTN.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("FacturationTN.Models.Client", b =>
                {
                    b.HasOne("FacturationTN.Models.CategorieClient", "Categorie")
                        .WithMany("Clients")
                        .HasForeignKey("CategorieClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("FacturationTN.Models.Facture", b =>
                {
                    b.HasOne("FacturationTN.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("FacturationTN.Models.LigneFacture", b =>
                {
                    b.HasOne("FacturationTN.Models.Facture", "Facture")
                        .WithMany("Lignes")
                        .HasForeignKey("FactureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturationTN.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facture");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("FacturationTN.Models.Produit", b =>
                {
                    b.HasOne("FacturationTN.Models.CategorieProduit", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieProduitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FacturationTN.Models.UniteMesure", "UniteMesure")
                        .WithMany("Produits")
                        .HasForeignKey("UniteMesureId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categorie");

                    b.Navigation("UniteMesure");
                });

            modelBuilder.Entity("FacturationTN.Models.CategorieClient", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("FacturationTN.Models.CategorieProduit", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("FacturationTN.Models.Facture", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("FacturationTN.Models.UniteMesure", b =>
                {
                    b.Navigation("Produits");
                });
#pragma warning restore 612, 618
        }
    }
}
